app:
  # env: local
  #  env: testing
  env: development
  #  env: staging
  #  env: production
  mock_auth: true
  name: golang_api
  is_maintenance_mode: false
  skip_maintenance_mode_token: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  port: 8000
db:
  user: kajiyamakentarou
  password: postgres
  host: 127.0.0.1
  name: postgres
  port: 5432
  schema: go_api